// The PreToolUse gate for the company-researcher agent.
//
// The researcher reads UNTRUSTED web pages, so a hostile page could try to talk it into reading local files, fetching
// internal URLs or running commands. agy's `tools:` allowlist is only advisory and does not gate MCP (docs/PHASE0.md),
// so the real gate is this hook: a small dependency-free Node script generated into the researcher workspace.
//
//   allow  finish, search_web
//   allow  read_url_content   only http(s), no credentials in the URL, and the host must be public (loopback, RFC1918,
//                             link-local, CGNAT, *.local/.internal, single-label hosts and anything whose DNS
//                             resolution lands on such an address are denied — no SSRF into the daemon or LAN)
//   allow  view_file/list_dir only inside the researcher workspace or ~/.gemini/antigravity-cli/brain/<conversationId>/
//                             (where agy spills fetched pages) — symlinks resolved, `..` neutralised
//   deny   everything else (run_command, write_to_file, browser_*, call_mcp_tool, subagents, ...)
//
// Fail-closed: any parse error, missing field, unexpected exception or hang prints a deny decision.

export const GATE_ALLOWED_TOOLS = ["finish", "search_web", "read_url_content", "view_file", "list_dir"] as const;

export interface GateScriptOptions {
  workspaceRoot: string;
  /** ~/.gemini/antigravity-cli/brain */
  brainRoot: string;
  /** Resolve hostnames and deny private results. Off only in offline tests. */
  dnsCheck: boolean;
}

export function renderGateScript(opts: GateScriptOptions): string {
  return `#!/usr/bin/env node
// Generated by agy-hq (setup wizard). Do not edit: it is rewritten before every research job.
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import dns from "node:dns/promises";

const WORKSPACE_ROOT = ${JSON.stringify(opts.workspaceRoot)};
const BRAIN_ROOT = ${JSON.stringify(opts.brainRoot)};
const DNS_CHECK = ${JSON.stringify(opts.dnsCheck)};
const ALLOWED_TOOLS = new Set(${JSON.stringify([...GATE_ALLOWED_TOOLS])});

let done = false;
function emit(decision, reason) {
  if (done) return;
  done = true;
  const out = decision === "allow" ? { decision: "allow" } : { decision: "deny", reason: "agy-hq setup gate: " + reason };
  process.stdout.write(JSON.stringify(out));
  process.exit(0);
}

// Hard stop well inside the hook timeout.
setTimeout(() => emit("deny", "gate timed out"), 12000).unref();

function readStdin() {
  return new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => (data += c));
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });
}

// ---- paths ----------------------------------------------------------------
function realish(p) {
  // realpath of the deepest existing ancestor + the not-yet-existing remainder (resolves symlinked ancestors).
  let cur = path.resolve(p);
  const rest = [];
  for (;;) {
    try {
      return path.join(fs.realpathSync(cur), ...rest.reverse());
    } catch {
      const parent = path.dirname(cur);
      if (parent === cur) return path.resolve(p);
      rest.push(path.basename(cur));
      cur = parent;
    }
  }
}
function inside(root, p) {
  const r = realish(root);
  const t = realish(p);
  return t === r || t.startsWith(r.endsWith(path.sep) ? r : r + path.sep);
}
function checkPath(value, roots) {
  if (typeof value !== "string" || value.length === 0 || value.includes("\\0")) return "missing or invalid path argument";
  let p = value.startsWith("file://") ? decodeURIComponent(value.slice(7)) : value;
  if (!path.isAbsolute(p)) return "path must be absolute";
  return roots.some((r) => inside(r, p)) ? null : "path is outside the research workspace";
}

// ---- hosts ----------------------------------------------------------------
function privateV4(ip) {
  const [a, b, c] = ip.split(".").map(Number);
  return (
    a === 0 || a === 10 || a === 127 || a >= 224 ||
    (a === 100 && b >= 64 && b <= 127) ||
    (a === 169 && b === 254) ||
    (a === 172 && b >= 16 && b <= 31) ||
    (a === 192 && b === 0 && c === 0) ||
    (a === 192 && b === 168) ||
    (a === 198 && (b === 18 || b === 19))
  );
}
function privateIp(ip) {
  const v = net.isIP(ip);
  if (v === 4) return privateV4(ip);
  if (v === 6) {
    const l = ip.toLowerCase();
    const mapped = l.match(/^::ffff:(\\d+\\.\\d+\\.\\d+\\.\\d+)$/);
    if (mapped) return privateV4(mapped[1]);
    if (l === "::" || l === "::1") return true;
    if (/^f[cd]/.test(l) || /^fe[89ab]/.test(l) || l.startsWith("ff")) return true;
    if (/^::ffff:/.test(l) || l.startsWith("64:ff9b:")) return true; // hex-form mapped/NAT64: refuse rather than parse
    return false;
  }
  return false;
}
async function checkUrl(value) {
  if (typeof value !== "string" || value.length === 0) return "missing URL";
  let u;
  try { u = new URL(value); } catch { return "invalid URL"; }
  if (u.protocol !== "http:" && u.protocol !== "https:") return "only http(s) URLs may be read";
  if (u.username || u.password) return "URLs with credentials are not allowed";
  const host = u.hostname.replace(/^\\[|\\]$/g, "").toLowerCase();
  if (!host) return "URL has no host";
  if (net.isIP(host)) return privateIp(host) ? "private/loopback address" : null;
  if (!host.includes(".") || /\\.(local|localhost|internal|lan|home|corp|intranet|private)$/.test(host) || host === "localhost") {
    return "internal hostname";
  }
  if (DNS_CHECK) {
    let addrs;
    try { addrs = await dns.lookup(host, { all: true }); } catch { return "hostname does not resolve"; }
    if (addrs.length === 0 || addrs.some((a) => privateIp(a.address))) return "hostname resolves to a private address";
  }
  return null;
}

// ---- decision -------------------------------------------------------------
async function decide(payload) {
  const call = payload && payload.toolCall;
  const name = call && call.name;
  const args = (call && call.args) || {};
  if (typeof name !== "string" || !name) return ["deny", "no tool name in request"];
  if (!ALLOWED_TOOLS.has(name)) return ["deny", 'tool "' + name + '" is not allowed for the company researcher'];
  if (name === "finish" || name === "search_web") return ["allow"];
  if (name === "read_url_content") {
    const why = await checkUrl(args.Url);
    return why ? ["deny", why] : ["allow"];
  }
  const conv = process.env.ANTIGRAVITY_CONVERSATION_ID || payload.conversationId;
  const roots = [WORKSPACE_ROOT];
  if (typeof conv === "string" && /^[A-Za-z0-9-]{8,64}$/.test(conv)) roots.push(path.join(BRAIN_ROOT, conv));
  const why = checkPath(name === "view_file" ? args.AbsolutePath : args.DirectoryPath, roots);
  return why ? ["deny", why] : ["allow"];
}

try {
  const raw = await readStdin();
  let payload;
  try { payload = JSON.parse(raw); } catch { emit("deny", "unreadable tool request"); }
  if (!payload || typeof payload !== "object") emit("deny", "unreadable tool request");
  const [decision, reason] = await decide(payload);
  emit(decision, reason);
} catch (err) {
  emit("deny", "internal error: " + (err && err.message ? err.message : String(err)));
}
`;
}
