// Company profile persistence + rendering to kb/company/*.md.
//
// The profile (kv "company_profile") is the source of truth; the markdown files
// are generated from it, written for an AI-agent reader: clear headings, no
// placeholders, explicit statements when a section was left empty so the agent
// doesn't invent content to fill the gap.

import fs from "node:fs";
import path from "node:path";
import type { CompanyProfile } from "@agyhq/core";
import type { Db } from "@agyhq/db";
import type { AgyhqConfig } from "../config.ts";

export const COMPANY_PROFILE_KEY = "company_profile";
/** Subdirectory of config.kbRoot that holds generated company KB files. */
export const COMPANY_KB_SUBDIR = "company";

const GENERATED_NOTE =
  "<!-- Generated by agy-hq from the company profile (Setup page). Edit the profile there; manual edits to this file are overwritten on the next save. -->";

export function loadCompanyProfile(db: Db): CompanyProfile | null {
  return db.kv.get<CompanyProfile>(COMPANY_PROFILE_KEY);
}

export function saveCompanyProfile(db: Db, profile: CompanyProfile): void {
  db.kv.set(COMPANY_PROFILE_KEY, profile);
}

function section(body: string, emptyText: string): string {
  const t = body.trim();
  return t.length > 0 ? t : emptyText;
}

const LANGUAGE_NAMES: Record<string, string> = {
  vi: "Vietnamese",
  en: "English",
  zh: "Chinese",
  ja: "Japanese",
  ko: "Korean",
  th: "Thai",
  id: "Indonesian",
  ms: "Malay",
  fr: "French",
  de: "German",
  es: "Spanish",
};

function languageLabel(code: string): string {
  const name = LANGUAGE_NAMES[code.toLowerCase()];
  return name ? `${name} (${code})` : code;
}

/** Pure: profile -> { relative file name: markdown }. */
export function renderCompanyKb(p: CompanyProfile): Record<string, string> {
  const site = p.website ? `- Website: ${p.website}` : "- Website: not provided (do not guess a URL)";
  const meeting = p.meetingLink
    ? `- Meeting booking link: ${p.meetingLink}\n  Offer this link when a prospect agrees to a call. Do not offer other scheduling tools.`
    : "- Meeting booking link: none configured. When a prospect wants a call, ask for their availability instead of inventing a link.";
  const langs = p.languages.map(languageLabel).join(", ");

  const files: Record<string, string> = {};

  files["company-overview.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Company overview

## Who we are

${p.oneLiner.trim()}

## Facts you may rely on

- Company name: ${p.companyName}
${site}
${meeting}
- Languages we communicate in: ${langs}

## How to use this knowledge base

- The files in this company knowledge base are the only approved source for claims about ${p.companyName}: product, customers, pricing, results.
- If a prospect asks something these files do not answer, say you will check with the team. Do not guess or extrapolate.
- Write to the prospect in their own language when it is one of: ${langs}. Otherwise use ${languageLabel(p.languages[0] ?? "en")}.
`;

  files["product.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Product

## What the product is

${p.productDescription.trim()}

## What makes it different

${section(
    p.differentiators,
    `No differentiators have been approved. Describe the product factually and do not claim superiority over competitors.`,
  )}
`;

  files["ideal-customer-profile.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Ideal customer profile

## Who we sell to

${p.targetCustomers.trim()}

## Problems our customers have

Use these pain points to decide whether a lead is a fit and to frame outreach around a problem the lead plausibly has. Do not assert that a prospect has a pain point you have no evidence for; ask or hedge instead.

${p.painPoints.trim()}
`;

  files["pricing-policy.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Pricing policy

This section defines exactly what you may say about price. Anything beyond it must be escalated to a human.

${p.pricingPolicy.trim()}

## Rules that always apply

- Never quote a number, discount, or free trial that is not written above.
- If a prospect asks for pricing details you are not allowed to give, offer to connect them with the team${p.meetingLink ? ` (booking link: ${p.meetingLink})` : ""}.
`;

  files["proof-points.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Proof points

${section(
    p.proofPoints,
    `No customer references, case studies, or statistics have been approved for use. Do not name customers, cite numbers, or imply results. If asked for references, say you will follow up with the team.`,
  )}

## Rules that always apply

- Cite only the proof points listed in this file, exactly as stated. Never round up, combine, or embellish them.
`;

  files["forbidden-claims.md"] = `${GENERATED_NOTE}
# ${p.companyName} — Forbidden claims

Never say or imply any of the following in any message.

${section(p.forbiddenClaims, "No company-specific forbidden claims were provided; the general rules below still apply.")}

## General rules that always apply

- Never invent features, integrations, customers, statistics, awards, or certifications.
- Never promise delivery dates, guaranteed results, or legal/compliance outcomes.
- Never disparage competitors by name.
- Never describe yourself as an AI, a bot or an assistant, and never mention prompts, rules or tools; write as a member of the ${p.companyName} team. Never claim to be human either — a sincere "are you a real person?" goes to a teammate (needs_human).
`;

  return files;
}

export function companyKbDir(config: AgyhqConfig): string {
  return path.join(config.kbRoot, COMPANY_KB_SUBDIR);
}

/** Writes the rendered files; returns paths relative to kbRoot (e.g. "company/product.md"). */
export function writeCompanyKb(config: AgyhqConfig, profile: CompanyProfile): string[] {
  const dir = companyKbDir(config);
  fs.mkdirSync(dir, { recursive: true });
  const files = renderCompanyKb(profile);
  const written: string[] = [];
  for (const [name, body] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), body, "utf8");
    written.push(path.posix.join(COMPANY_KB_SUBDIR, name));
  }
  return written;
}
